### ISSUE TITLE
不能正确转换私聊信息的“user_id”

### ISSUE THREAD

**Issue by Artificialheaven** [molehzy/go-cqhttp-e#1]
系统环境： Windows7
语言版本：易语言5.9
相关库：E2EE 23220版

调用的代码
CQ.发送私聊消息（“2149999999”，“测试”）

返回信息
{"action":"send_private_msg","params":{"user_id":-2144967297,"message":"测试成功","auto_escape":true}}

大约在2139999999这个数字后会产生错误，具体数字不明。该BUG可能严重影响插件，在目前的QQ号已经有超大多数为9、10、11甚至更多位数的号码。

**Comment by molehzy** [comment]
到整数() 改为 到长整数() 即可
