### ISSUE TITLE
调用库命令“到JSON”时传递了过多的参数

### ISSUE THREAD

**Issue by Artificialheaven** [molehzy/go-cqhttp-e#2]
错误所处位置: 模块:"go-cqhttp-e"; 程序集:"类_CQHTTP"; 子程序:"HTTP发送私聊消息"
错误(10045): 调用库命令“到JSON”时传递了过多的参数。

**Comment by molehzy** [comment]
无法复现，如果是自己下源码编译，请确保E2EE版本是2.7.2
